### ISSUE TITLE
How to install and use your script?

### ISSUE THREAD

**Issue by EmbeddedDevver** [acte-technology/thingsboard-js-sdk#1]
I am new to this.
So I installed NPM on windows.

Then installed your script using your install script. 

Where from here should I go to so I can have a local webpage of your site: https://acte.ltd/iot/client/login

With your website (that is awesome to use!) I cannot remove telemetry from the future. By a programming error, I added telemetry with the year 2026. Your website only goes from now till past, Not future.

Hope you can help me by installing your script on my local PC.

Thank you

**Comment by AdrienAdB** [comment]
Hello, sorry for late reply, I didn't receive notification.

To recreate like our website page, you should first create a login page with (host, username, password).
OnSubmit form:
- use connect() function: https://github.com/acte-technology/thingsboard-js-sdk#connect-with-userpassword
- save token, host, user in sessionStorage and redirect to dashboard page

When dashboard page loads:
- getDevices(): https://github.com/acte-technology/thingsboard-js-sdk#get-tenant-devices
- when a device is selected: getKeys and other informations.

**Comment by AdrienAdB** [comment]
I forgot, you have a React example in: https://github.com/acte-technology/thingsboard-js-sdk/blob/master/docs/reactjs.js
