### ISSUE TITLE
Unable to import within NodeJS

### ISSUE THREAD

**Issue by timvahlbrock** [acte-technology/thingsboard-js-sdk#2]
The module cannot be imported into the properly. When imported using the ES6 import Syntax, the nodejs package needs to be of type "module". However. The module uses the import syntax itself, without having the "module" type, leading to an exception as well. The alternative version - the import via `require` doesn't work either for the same reasons.

**Comment by AdrienAdB** [comment]
Hi @timvahlbrock, we only used on client side using ReactJs so far. It should not be long to test and make modifications for NodeJS, working on it....

**Comment by AdrienAdB** [comment]
Dev branch created: https://github.com/acte-technology/thingsboard-js-sdk/tree/dev
- It didn't brake current ReactJs demo.
- Running ```$ node index.js```didn't make any error, but didn't tested more yet.

**Comment by timvahlbrock** [comment]
I've just tried to just set `type: "module"` within the package.json myself. Works just as well and allows to keep the more modern import statements. However, this might complicate things with users of older Node versions.

**Comment by AdrienAdB** [comment]
Shall we merge dev branch with require() imports or simply add ```type: "module"``` in package.json ?
Could you suggest a PR?

**Comment by timvahlbrock** [comment]
Wait a second, I just read through your comment again. I wasn't able to test the ReactJS demo. If that works too, I think just adding `type: "module"` might be the cleaner option.

**Comment by timvahlbrock** [comment]
> Wait a second, I just read through your comment again. I wasn't able to test the ReactJS demo. If that works too, I think just adding `type: "module"` might be the cleaner option.

with which I meant to say, I don't know how you tested the react demo. So you either need to test it yourself or tell me how to do it.

**Comment by AdrienAdB** [comment]
Hi @timvahlbrock, for ReactJS, this links are using latest version v0.0.11:
- https://acte.ltd/iot/client/login
- https://acte.ltd/iot/dashboards/energy
- https://acte.ltd/iot/dashboards/aqi

I modified index.js to be Common JS compliant: Import with Node is ok now.
However, I can see sessionStorage is still in used, so nodejs will flag an error: https://github.com/acte-technology/thingsboard-js-sdk/blob/master/index.js#L47.

**Comment by AdrienAdB** [comment]
> > Wait a second, I just read through your comment again. I wasn't able to test the ReactJS demo. If that works too, I think just adding `type: "module"` might be the cleaner option.
> 
> with which I meant to say, I don't know how you tested the react demo. So you either need to test it yourself or tell me how to do it.

Also an example here: https://github.com/acte-technology/thingsboard-js-sdk/blob/master/docs/reactjs.js

**Comment by AdrienAdB** [comment]
v0.1.0. Tested with NodeJS.
Example in docs/
https://github.com/acte-technology/thingsboard-js-sdk/blob/master/docs/server.js

**Comment by timvahlbrock** [comment]
> > > Wait a second, I just read through your comment again. I wasn't able to test the ReactJS demo. If that works too, I think just adding `type: "module"` might be the cleaner option.
> > 
> > 
> > with which I meant to say, I don't know how you tested the react demo. So you either need to test it yourself or tell me how to do it.
> 
> Also an example here: https://github.com/acte-technology/thingsboard-js-sdk/blob/master/docs/reactjs.js

Yes I've seen that, but I didn't know how exactly you used the example. Afterall I didn't actually use this library, as I just wanted to  test sending sample data to our own ThingsBoard instance, which was just as easy by using an mqtt package. I attempted to use this library at first and just realized that it wasn't includable in NodeJS and wanted to bring this to your attention.

**Comment by AdrienAdB** [comment]
Yes, if you only need to send some data, a simple POST telemetry with device api is enough and done in a few lines.
But thanks, you pointed this out it and now it works for NodeJS ;-)

I am closing issue.
