### ISSUE TITLE
Connect by websocket example

### ISSUE THREAD

**Issue by thinhvotruong35** [acte-technology/thingsboard-js-sdk#4]
Hello, I'm newbie in ReactJS trying to collect data from device's telemetry to show on ReactJS. Can you have code example to do it?

**Comment by AdrienAdB** [comment]
Hello,
We have a basic example here for React: https://github.com/acte-technology/thingsboard-js-sdk/blob/master/docs/reactjs.js

For WebSocket, you can run this, and check response from callback:
https://github.com/acte-technology/thingsboard-js-sdk#wss-websocket-subscribe

**Comment by thinhvotruong35** [comment]
Thanks for your quick reply, I have use example to connect successful by user and password. I consider about how to check WebSocket id, does it is a const? and how to check response from callback

**Comment by AdrienAdB** [comment]
Yes it is a constant, you can assign random ID to each socket.
Please find extract from 1 of my project:


```js

const client = new tbClient({
  host: "your-host",
  publicId: "public-id"
});

const now = Date.now();
const mtd = now-3600000;

const device1 = {
  cmdId: 10,
  entityId: 'your-access-token-1',
  startTs: mtd,
  endTs: now
};

const device2 = {
  cmdId: 11,
  entityId: 'your-access-token-2',
  startTs: mtd,
  endTs: now
};

const MySocket = (props) => {

    const [ connected, setConnected ] = useState(false);

    const openSocket = async () => {

      let token = await client.connect(true);

      if(token){

        setConnected(true);

        client.subscribe(device1, async function(response){


          if(response && response.data){
             console.log('device1', response.data);
          }


        });

      } else {
        setTimeout(() => openSocket(), 5000);
      }

    }

    useEffect(() => {
      if(!connected){ openSocket(); }
    },[connected]);

    return(<div></div>);

}
```

**Comment by thinhvotruong35** [comment]
After run your code, I got this error, I think because wronged about the "publicId", does it is the device id? 
![image](https://user-images.githubusercontent.com/63631081/166112246-633e4bf1-2c1b-4b06-8b01-853d5a95d786.png)

**Comment by AdrienAdB** [comment]
I just created a new issue #5 , publicId belongs to a public dashboard.
You can connect with user/password auth instead or creating a public dashboard.

**Comment by thinhvotruong35** [comment]
Thank you, It seems app worked but it say "WebSocket Closed", do you have any idea for this
![image](https://user-images.githubusercontent.com/63631081/166854252-52804040-f94c-4567-8935-6b5a0075c747.png)

**Comment by AdrienAdB** [comment]
Yes, sorry for late reply. 
When socket is closed, it's response becomes null.
You can simply run openSocket() if response == null.
